### ISSUE TITLE
Arduino IDE can not compile

### ISSUE THREAD

**Issue by shadowroot2** [markohoepken/rx5808_pro_osd#1]
Hello, can not compile sources

rx5808_pro_osd.ino:81:24: fatal error: MemoryFree.h: No such file or directory

**Comment by markohoepken** [comment]
Hi,

just comment out line 81
like:
//#include <MemoryFree.h>

This is  for debug only.

I will fix it in next release.

Marko

**Comment by shadowroot2** [comment]
Now it is

In file included from C:\Program Files (x86)\Arduino\libraries\FastSerial/FastSerial.h:56:0,
                 from ArduCam_Max7456.cpp:2:
C:\Program Files (x86)\Arduino\libraries\FastSerial/BetterStream.h:16:36: fatal error: ../AP_Common/AP_Common.h: No such file or directory
 #include "../AP_Common/AP_Common.h"
                                    ^
compilation terminated.

**Comment by markohoepken** [comment]
Yes also known.

This library is comming form another project, but used by the MAX driver.

Let me collect the libs right now, Expect a release in the next hour, that should work.

Than all required libs should be in my libs folder... stand by.

Marko

**Comment by markohoepken** [comment]
Plese check this some days ago:
\http://fpv-community.de/showthread.php?68795-RX5808-pro-mit-OSD&p=883201&viewfull=1#post883201

**Comment by shadowroot2** [comment]
Thanks! I try to mod fathark dominators, with this...

**Comment by shadowroot2** [comment]
Updated. Now:

In file included from C:\Program Files (x86)\Arduino\libraries\FastSerial/BetterStream.h:16:0,
                 from C:\Program Files (x86)\Arduino\libraries\FastSerial/FastSerial.h:56,
                 from ArduCam_Max7456.cpp:2:
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h: In function 'int strcasecmp_P(const char_, const prog_char_t_)':
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:108:38: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
     return strcasecmp_P(str1, (const prog_char _)pstr);
                                      ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:108:38: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:108:32: error: expected primary-expression before 'const'
     return strcasecmp_P(str1, (const prog_char *)pstr);
                                ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:108:32: error: expected ')' before 'const'
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h: In function 'int strcmp_P(const char_, const prog_char_t_)':
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:113:34: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
     return strcmp_P(str1, (const prog_char *)pstr);
                                  ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:113:34: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:113:28: error: expected primary-expression before 'const'
     return strcmp_P(str1, (const prog_char *)pstr);
                            ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:113:28: error: expected ')' before 'const'
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h: In function 'size_t strlen_P(const prog_char_t_)':
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:118:28: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
     return strlen_P((const prog_char _)pstr);
                            ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:118:28: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:118:22: error: expected primary-expression before 'const'
     return strlen_P((const prog_char *)pstr);
                      ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:118:22: error: expected ')' before 'const'
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h: In function 'void_ memcpy_P(void_, const prog_char_t_, size_t)':
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:123:34: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
     return memcpy_P(dest, (const prog_char _)src, n);
                                  ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:123:34: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:123:28: error: expected primary-expression before 'const'
     return memcpy_P(dest, (const prog_char *)src, n);
                            ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:123:28: error: expected ')' before 'const'
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h: In function 'char_ strncpy_P(char_, const prog_char_t_, size_t)':
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:148:37: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
     return strncpy_P(buffer, (const prog_char _)pstr, buffer_size);
                                     ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:148:37: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:148:31: error: expected primary-expression before 'const'
     return strncpy_P(buffer, (const prog_char *)pstr, buffer_size);
                               ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:148:31: error: expected ')' before 'const'
In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/WString.h:29:0,
                 from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:26,
                 from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Stream.h:26,
                 from C:\Program Files (x86)\Arduino\libraries\FastSerial/BetterStream.h:14,
                 from C:\Program Files (x86)\Arduino\libraries\FastSerial/FastSerial.h:56,
                 from ArduCam_Max7456.cpp:2:
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h: In function 'uintptr_t pgm_read_pointer(const void_)':
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:165:47: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
             u.a[i] = pgm_read_byte(i + (const prog_char *)s);
                                               ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:165:47: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:165:41: error: expected primary-expression before 'const'
             u.a[i] = pgm_read_byte(i + (const prog_char *)s);
                                         ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:165:41: error: expected ')' before 'const'
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:165:22: error: expected ')' before ';' token
             u.a[i] = pgm_read_byte(i + (const prog_char *)s);
                      ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/../AP_Common/AP_Common.h:165:22: error: expected ')' before ';' token
In file included from C:\Program Files (x86)\Arduino\libraries\FastSerial/FastSerial.h:56:0,
                 from ArduCam_Max7456.cpp:2:
C:\Program Files (x86)\Arduino\libraries\FastSerial/BetterStream.h: At global scope:
C:\Program Files (x86)\Arduino\libraries\FastSerial/BetterStream.h:28:41: error: 'prog_char' does not name a type
         void            _printf_P(const prog_char *, ...);
                                         ^
C:\Program Files (x86)\Arduino\libraries\FastSerial/BetterStream.h:28:51: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
         void            _printf_P(const prog_char *, ...);

**Comment by markohoepken** [comment]
Hi,

Just created a new full package.

I compiled with Adruion 1.0.5 on Windows without any problems...

There are some warning on compile, but since these are only from lbs I used from extern, I ignored them.

You may think about using my compiled hex file in the new release.

Sorry, Marko

**Comment by shadowroot2** [comment]
I use Arduino IDE 1.6.5, now will try with 1.0.5.
Can not use hex, because I wont do some changes in code. I have Whitespy OSD (minim osd with extra pins for bat1,bat2,rssi). Need compare pins. And Fathsark has only 2 buttons for change channels. I think use 1+2 at same time as 3th button.

**Comment by shadowroot2** [comment]
In 1.0.5 compiled without errors. Thank you!

**Comment by markohoepken** [comment]
OK. Thanks for the feedback.

About the buttons: You need realy just 2. The 3rd is for comfort only.

To do just the "up" and the "mode" button.
The down helps on manual mode, because you must go throug all channels when you missed yours.

Please let me know, how you did it with the Whitespy OSD, that we just offer this branch for others.

Marko

**Comment by markohoepken** [comment]
I added a note in the Wiki, that only 1.0.5 will compile... with all libs.

Thanks Marko

**Comment by markohoepken** [comment]
Solved
